import 'ts-mongoose/plugin';

export * from './afterschool';
export * from './afterschool-application';
export * from './circle';
export * from './circle-application';
export * from './config';
export * from './meal';
export * from './outgo-request';
export * from './attendance-log';
export * from './place';
export * from './notice';
export * from './timetable';
export * from './file';
export * from './mentoring';
export * from './mentoring-application';
export * from './dets';
export * from './dets-application';
export * from './user-latest-place';
export * from './temporary-password';
export * from './token';
export * from './permission';
export * from './user-type';
export * from './washer';
