import 'ts-mongoose/plugin';

export * from './afterschool';
export * from './afterschool-application';
export * from './user';
export * from './circle';
export * from './circle-application';
export * from './config';
export * from './ingang-application';
export * from './meal';
export * from './outgo-request';
export * from './attendance-log';
export * from './place';
export * from './notice';
export * from './timetable';
export * from './file';
export * from './mentoring';
export * from './mentoring-application';
export * from './dets';
export * from './dets-application';
